### ISSUE TITLE
air fails to install in go 1.24

### ISSUE THREAD

**Issue by mattgen88** [air-verse/air#741]
```
go install github.com/air-verse/air@latest
go: downloading github.com/air-verse/air v1.61.7
go: downloading dario.cat/mergo v1.0.1
go: downloading github.com/creack/pty v1.1.23
go: downloading github.com/fatih/color v1.17.0
go: downloading github.com/fsnotify/fsnotify v1.7.0
go: downloading github.com/gohugoio/hugo v0.134.3
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading golang.org/x/sys v0.25.0
go: downloading github.com/bep/godartsass v1.2.0
go: downloading github.com/bep/godartsass/v2 v2.1.0
go: downloading github.com/bep/golibsass v1.2.0
go: downloading github.com/pelletier/go-toml/v2 v2.2.3
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/tdewolff/parse/v2 v2.7.15
go: downloading github.com/cli/safeexec v1.0.1
go: downloading google.golang.org/protobuf v1.34.2
go: downloading golang.org/x/text v0.18.0
go: downloading github.com/spf13/cast v1.7.0
go: downloading github.com/gobwas/glob v0.2.3

# runtime/cgo
In file included from _cgo_export.c:3:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
after upgrading to 1.24, air cannot be installed as it fails to compile. 
Tried on:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```
and 
```
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

**Comment by mattgen88** [comment]
JK, it actually looks like an environment issue
